# to control a group of similar pods
kind: Deployment

apiVersion: apps/v1

metadata:
  # name of the deployment
  name: asset-management-server-deployment
  # separate namespace to organize cluster's resource
  namespace: asset
  # labels for the deployment
  labels:
    app: asset-management-server-deployment

spec:
  # copies of pod
  replicas: 1

  # pods which is needed to be managed
  selector:
    matchLabels:
      app: asset-management-server-pod

  template:
    metadata:
      # labels for the pod
      labels:
        app: asset-management-server-pod

    spec:
      # container specification
      containers:
        - name: asset-management-server
          image: karan1801/asset-management-server
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
